# Generated by Django 5.0.3 on 2024-03-06 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_rename_reviews_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='featured_image',
            field=models.ImageField(blank=True, default='icon.svg', null=True, upload_to=''),
        ),
    ]
